### PR TITLE
Output phased genotypes

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by nh13** [comment]
@ldgauthier @lbergelson @davidbenjamin @droazen
This is an additional commit to https://github.com/broadinstitute/gatk/pull/5318 that attempts to make the genotype phased.  I say attempts, since I have not modified any of the tests.  

I think there is some input I would request:
1. This assumes diploid genotypes (as I think the phasing code already does).  Is this correct?
2. I need to reverse the alleles when phasing multiple alleles across a phasing-set.  This may make the various FORMAT fields out of order for this sample.  I have already swapped the `AD` and `PL` fields, but I don't see a generic way to this for any extended attribute.  Since the extended attributes are only added by the `HaplotypeCallerGenotypingEngine` or `SomaticGenotypingEngine` ahead of the call to `phaseCalls`, I think this is fine.  What do you think?

**Comment by davidbenjamin** [comment]
What about downstream filtering code that assumes the reference allele is the first?  I think `FilterMutectCalls` does this in some places.  Not sure about VQSR or about Sam F's work.  Not to mention pipelines that use GATK output.  I guess I don't mind breaking those a bit as long as we have never given a guarantee that the ref allele is first or suggested that this can be relied on.  That depends on what the comms team has put on the forum etc.

**Comment by ldgauthier** [comment]
The PLs definitely assume reference first in the spec (see the GL description in http://samtools.github.io/hts-specs/VCFv4.2.pdf).  I believe AD is more of a GATK convention, so it's not addressed in the spec, but I'm guessing HTSJDK has some assumptions.  Have you looked at what the VariantContextBuilder does? Given that it pads out ADs for alts seen in other samples it must make some assumption about the ordering.

VQSR doesn't look at genotypes.

**Comment by nh13** [comment]
@ldgauthier "canonical order" is used for the GL description for v4.2.  I don't know what that means since it isn't defined anywhere.  But assuming you're correct, that the PLs are listed in assuming reference first, then alts in order, I don't see any problem with the genotype field being for example `0|2` or `2|0`, do you?

@davidbenjamin I'll try to take a look at downstream tools, especially GATK's `FilterMutectCalls` and htsjdk, but what is Sam F's work (can you point me to it so I can look)?   

A compromise is to have a command line option or environment variable to turn it on, and as folks use it and we discover places we need to fix, we can do that iteratively.  Of course, I'd be the first user and I am happy to submit PRs as I encounter issues.  Does that seem like a reasonably conservative compromise?

**Comment by ldgauthier** [comment]
Sam F.'s work doesn't look at genotypes either.

In the old PhaseByTransmission integrationtest results there's:
`1       10150   .       C       T       99      PASS    TestDescription=HomRef/Het/Het  GT:AD:GQ:PL:TP  1|0:30,20:50:50,0,200:46`
There the AD supports the PLs if they are both ordered reference-first, which is how I interpret "canonical order" for PLs.  The corresponding code does not reorder any of the genotype attributes for 1|0 phased hets.

ReadBackedPhasing does not appear to output phased genotypes.

**Comment by nh13** [comment]
@ldgauthier thanks for digging into that!  So how would you recommend I proceed.  This would be really nice feature (phasing) to have in HC.

**Comment by ldgauthier** [comment]
I think the allele ordering and pipe delimiter (i.e. what you have for the genotype now) is great, but the reverse ordering of the ADs and PLs is unnecessary.  I would prefer that the genotype phasing be optional and controlled by a commandline argument.

**Pull request merged**
